### ISSUE TITLE
We planned to kick you out quite a while ago

### ISSUE THREAD

**Issue by TheGloriousDuck** [YeahOMA/MonsoonRip#2]
go and cry about it
this src leak hasn't done anything to stop the client, we already got a lot done since you were last here

**Comment by YeahOMA** [comment]
Blatant cheating is dead anyways, I was planning to leak source ever since migration started Lmfao. Good luck making money off of this now.

**Comment by YeahOMA** [comment]
Tell quickdaffy if he prefers chicken wings or pizza since I'll gladly send it to his house

**Comment by YeahOMA** [comment]
And do you really think this soon to be $8 client is going to compete with ZeroDay or any other client? Sure it may be cheaper but all the bypasses and visuals are ass, not to mention the owner is a 14 year old

**Comment by quickdaffy** [comment]
????
- client is $5
- we’re not trying to compete with zeroday?
- you’re also 14???
- blatant cheating isn’t going to die lmaoo
- we already have had like 8 people wanting to buy since you leaked

**Comment by xxxOMA** [comment]
they clearly haven't seen the $$$ amazing $$$ bypasses that don't get patched in a few days, and yes blatant cheating is going to die, cry about it, what's your argument? keep crying that I leaked your shit skid retard

**Comment by xxxOMA** [comment]
when did I say you're trying to be better than zeroday Lmfao? I said literally everytime would buy ZeroDay when b21 releases for $10 and not this shit skid for $5 with no bypasses that last for even 2 days

**Comment by xxxOMA** [comment]
I'm 15 retard
